spring:
  application:
    name: aiservice
  data:
    mongodb:
      username: canberk
      password: canberk
      host: localhost
      port: 27017
      database: fitnessrecommendation
      authentication-database: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8083
