spring:
  data:
    mongodb:
      username: canberk
      password: canberk
      host: localhost
      port: 27017
      database: fitnessrecommendation
      authentication-database: admin
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}

server:
  port: 8083
