spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/fitness_user
    username: postgres
    password : postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081
