spring:
  application:
    name: activity-service
  data:
    mongodb:
      username: canberk
      password: canberk
      host: localhost
      port: 27017
      database: fitnessactivity
      authentication-database: admin
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082
