spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5433/fitness_user
    username: postgres
    password : postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
